language: python
services:
    - mysql
    - postgresql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
env:
    - TESTING_DATABASE_URL='mysql+pymysql://root@localhost/ctfd'
    - TESTING_DATABASE_URL='sqlite://'
    - TESTING_DATABASE_URL='postgres://postgres@localhost/ctfd'
python:
    - 2.7
    - 3.6
install:
    - pip install -r development.txt
before_script:
    - psql -c 'create database ctfd;' -U postgres
script:
    - pycodestyle --ignore E501,E712,E402 CTFd/ tests/
    - nosetests -v -d --with-randomly
after_success:
    - codecov
