language: python
dist: xenial
cache:
    - pip
    - yarn
services:
    - mysql
    - postgresql
    - redis-server
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.6
    - python3-pip
env:
    - TESTING_DATABASE_URL='mysql+pymysql://root@localhost/ctfd'
    - TESTING_DATABASE_URL='sqlite://'
    - TESTING_DATABASE_URL='postgres://postgres@localhost/ctfd'
python:
    - 3.6
before_install:
    - sudo rm -f /etc/boto.cfg
    - export AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
    - export AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
install:
    - pip install -r development.txt
    - yarn install --non-interactive
    - yarn global add prettier@1.17.0
before_script:
    - psql -c 'create database ctfd;' -U postgres
script:
    - make lint
    - make test
after_success:
    - codecov
